pyclean () {
    find . -name "*.pyc" | xargs -I {} rm -v "{}"
    find . -type d -name "__pycache__" -delete
}

# Fix for boxen in zsh
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8


export GOPATH="$HOME/Code/go"


export PATH=/usr/local/bin:$HOME/bin:$GOPATH/bin:$PATH


if which pyenv > /dev/null; then
    eval "$(pyenv init -)";
fi
