[[shades]]
name = "extradark"
start_time = 16:00:00
end_time = 20:00:00

[[shades]]
name = "blue-light-filter"
start_time = 20:00:00
end_time = 03:00:00


[[shades]]
name = "extradark"
start_time = 03:00:00
end_time = 07:00:00